### ISSUE TITLE
documentation link broken

### ISSUE THREAD

**Issue by cylwin** [cozy/cozy-db#10]
Hey,

I found this link in the README.md : `Read [the doc](http://aenario.github.io/cozydb/doc/DOCINDEX.md.html)`
It's broken because the repo was moved.

I didn't fix this in a PR because I didn't found the right link.

Bye

**Comment by jsilvestre** [comment]
Thank you for the report. It has been fixed by 51ed5a4e940bb54e998f561b1093bee7c8149322.

**Comment by aenario** [comment]
This should have been fixed in v0.0.9
