### ISSUE TITLE
updateAttributes doesn't return the updated doc

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-db#18]
When doing a merge, the data system only returns `success: true`, not the updated document. So we don't get the updated document in the callback of updateAttributes.
I don't know what's the expected behavior, so I'm not providing a patch.

**Comment by frankrousseau** [comment]
Thank you for reporting @clochix

**Comment by aenario** [comment]
:warning: This might be a breaking change in some apps, but I agree it is the right API. Need to be changed on the DS too.

**Comment by jsilvestre** [comment]
~~This make it hard to provide a clean documentation, so I'm looking forward to implement it.~~

I don't know why I thought it was not working, because it is (https://github.com/cozy/cozy-db/blob/master/src/model.coffee#L390), but the issue has not been closed. Can you please confirm @aenario?

**Comment by jsilvestre** [comment]
Ok, further testing shows that:

This works:

``` coffeescript
note.updateAttributes {key: value}, (err, updated) ->
```

This doesn't:

``` coffeescript
Note.updateAttributes id, {key: value}, (err, updated) ->
```

It is logical since the code is not the same for both (see: https://github.com/cozy/cozy-db/blob/master/src/model.coffee#L94).

The problem is that we don't know the current model's value, so I think it's a Data System issue rather than a cozy-db issue. Thoughts?

**Comment by aenario** [comment]
Yes, it should be changed on the DS so that calls to /merge returns the whole updated document, then cozydb can return it for both static and instance updateAttributes.

**Comment by aenario** [comment]
I am just affraid of some applications relying on body.success is true

**Comment by poupotte** [comment]
This issue is not relevant anymore because we're working on a new stack version.
