### ISSUE TITLE
"cozydb failed to load" on Archlinux

### ISSUE THREAD

**Issue by babolivier** [cozy/cozy-db#23]
Hey there,

Whenever I try to launch the americano server of my Cozy app, I get this error:

<pre>
$ coffee server.coffee
[2015-06-19 10:26:19:427] info - americano | add plugin: cozydb
template - all request creation...
[2015-06-19 10:26:19:494] error - americano | cozydb failed to load.
[Error: "name" and "value" are required for setHeader().]</pre>

The rest (routes and development configuration) loads and the server starts.

Using Archlinux (all packages up to date). I don't think it comes from my app since I have the same issue with the templates.

**Comment by aenario** [comment]
Hi @babolivier , you've got the wrong version of Node. cozydb (as most of cozy) is only compatible with node 0.10

**Comment by babolivier** [comment]
Oh, OK, thanks!

**Comment by clochix** [comment]
@babolivier is it ok now ? Could we close this ?

**Comment by babolivier** [comment]
Yup!
