### ISSUE TITLE
instance.save changed semantics

### ISSUE THREAD

**Issue by aenario** [cozy/cozy-db#24]
So, by mistake I changed model.save to not create the model if it doesnt exist.
When converting applications to cozydb, I removed all .save and replaced them by .updateAttributes

It's better, because save will erase unknown fields :
Let's say app 1 has a Book model, with schema {isbn, title}
And app 2 has a Book model, with schema {isbn, title, summary}
And we update the model with a .save, the summary will be lost 

I think we should remove the .save method.

**Comment by clochix** [comment]
Could we at least add a deprecation warning linked to this ticket ?

**Comment by bnjbvr** [comment]
There's one thing that's intensively used in Kresus and that I don't know how to do without save:

```
let obj = DocType.get(id);
obj.attribute = undefined; // or equivalently, delete obj.attribute
obj.save(callback);
```

That is, delete an attribute value. If you use updateAttr for that, the update object is going to resemble `{attribute: undefined}`, which is unfortunately equivalent to `{}`.

How can i deal with this if you remove the `.save` method? Wouldn't it be simpler to Just Fix (c) the introduced bug?

**Comment by clochix** [comment]
@bnjbvr what about adding a deleteAttribute method?

**Comment by bnjbvr** [comment]
@clochix That would work for me.

**Comment by poupotte** [comment]
This issue is not relevant anymore because we're working on a new Stack version.
