### ISSUE TITLE
pouchdb adapter's "define" function expects an anonymous function

### ISSUE THREAD

**Issue by bnjbvr** [cozy/cozy-db#33]
as shown in https://github.com/cozy/cozy-db/blob/master/src/pouchmodel.coffee#L193-L198

As a matter of fact, having a request which is a named function (e.g. `bank: { myRequest: function myRequest() { emit(doc.id, doc); }}`) will trigger a syntax error at some point, because the constructed function doesn't make sense.

**Comment by bnjbvr** [comment]
(and also a `try{} catch{}` block would be needed around the call to the Function ctor, to provide a more explicit error message in case it failed here :-))

**Comment by bnjbvr** [comment]
Note that by default, babeljs has a transformer that adds names to block scoped variables:

## In

`let v = function() {};`

## Out

`let v = function v() {};`

So the pouchdb define's function behavior + babeljs behavior = kaboom.

**Comment by clochix** [comment]
Thanks for reporting @bnjbvr ☺
@aenario any idea?
