### ISSUE TITLE
pouchdb requestDestroy's function calls request with the wrong API

### ISSUE THREAD

**Issue by bnjbvr** [cozy/cozy-db#34]
`request` expects `(name, params, callback)`, and https://github.com/cozy/cozy-db/blob/master/src/pouchmodel.coffee#L243

**Comment by bnjbvr** [comment]
(this is causing https://github.com/bnjbvr/kresus/issues/170 )

**Comment by clochix** [comment]
Hi @bnjbvr, thanks for reporting, a PR would be much appreciated ;-)
