### ISSUE TITLE
Broken support for reduce functions

### ISSUE THREAD

**Issue by aenario** [cozy/cozy-db#8]
https://github.com/cozy/cozy-db/blob/4aba05e91da1ed3360fadc061c0e97211f92dce3/src/cozymodel.coffee#L174

Lack a .toString(), need to check if it works with string reduce such as '_count'

**Comment by frankrousseau** [comment]
It looks like a big bug. Is it?

**Comment by jsilvestre** [comment]
It is indeed, it's a regression. I noticed it when working with a map/reduce in Calendar.

**Comment by frankrousseau** [comment]
Ok @aenario, if you don't work on it, notify us.

**Comment by aenario** [comment]
will work on it this afternoon

**Comment by aenario** [comment]
Ok, I mismanaged github redirect & fork and just pushed it to cozy master. Feel free to review.
